### ISSUE TITLE
大佬 部署能说的更详细一点吗 小白不太懂

### ISSUE THREAD

**Issue by flyjinhui** [Steve0x2a/DLimiter#1]
是直接解压文件到群晖本地，然后ssh 运行那个代码就可以了吗？

**Comment by Steve0x2a** [comment]
补充了一些文档，现在应该足够简单了。

**Comment by flyjinhui** [comment]
> 补充了一些文档，现在应该足够简单了。

谢谢大佬 终于用上了

**Comment by flyjinhui** [comment]
大佬，麻烦看看报错怎么回事 下面是docker的日志
<!DOCTYPE html>
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style>body{font-family:"Lucida Console",Consola,Monaco,Monospace,"Courier New",Courier,Serif;}h2{text-align:center;}table{width:95%;border-collapse:collapse;}table,th,td{border:1px solid black;}td{white-space:nowrap;text-align:left;}</style>
</head>
<body>
<h2>Dlimiter1</h2>
<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2023-02-05T17:35:38.905740266Z</td><td>stdout</td><td>_rtoml.TomlParsingError:&nbsp;unexpected&nbsp;character&nbsp;found:&nbsp;`\u{89e6}`&nbsp;at&nbsp;line&nbsp;21&nbsp;column&nbsp;20
</td></tr>
<tr><td>2023-02-05T17:35:38.905641986Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_rtoml.deserialize(toml)
</td></tr>
<tr><td>2023-02-05T17:35:38.905554722Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/site-packages/rtoml/__init__.py",&nbsp;line&nbsp;35,&nbsp;in&nbsp;loads
</td></tr>
<tr><td>2023-02-05T17:35:38.905518666Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;loads(toml)
</td></tr>
<tr><td>2023-02-05T17:35:38.905302217Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/site-packages/rtoml/__init__.py",&nbsp;line&nbsp;26,&nbsp;in&nbsp;load
</td></tr>
<tr><td>2023-02-05T17:35:38.905268466Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;cfg&nbsp;=&nbsp;edict(rtoml.load(Path(self.path)))
</td></tr>
<tr><td>2023-02-05T17:35:38.905229675Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/conf/__init__.py",&nbsp;line&nbsp;14,&nbsp;in&nbsp;parse_conf
</td></tr>
<tr><td>2023-02-05T17:35:38.905179948Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;config&nbsp;=&nbsp;Config(path="./conf/config.toml").parse_conf()
</td></tr>
<tr><td>2023-02-05T17:35:38.905095987Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/conf/__init__.py",&nbsp;line&nbsp;21,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.905057739Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;conf&nbsp;import&nbsp;config
</td></tr>
<tr><td>2023-02-05T17:35:38.904902781Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/utils/limiter.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.904871203Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;utils.limiter&nbsp;import&nbsp;player_apply_limit
</td></tr>
<tr><td>2023-02-05T17:35:38.904824378Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/routes/emby.py",&nbsp;line&nbsp;3,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.904783498Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;routes.emby&nbsp;import&nbsp;bp_emby
</td></tr>
<tr><td>2023-02-05T17:35:38.904716885Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/routes/__init__.py",&nbsp;line&nbsp;2,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.904676582Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;routes&nbsp;import&nbsp;bp_player
</td></tr>
<tr><td>2023-02-05T17:35:38.904578447Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/main.py",&nbsp;line&nbsp;2,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.904491304Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap&gt;",&nbsp;line&nbsp;241,&nbsp;in&nbsp;_call_with_frames_removed
</td></tr>
<tr><td>2023-02-05T17:35:38.904392526Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap_external&gt;",&nbsp;line&nbsp;883,&nbsp;in&nbsp;exec_module
</td></tr>
<tr><td>2023-02-05T17:35:38.904284603Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap&gt;",&nbsp;line&nbsp;688,&nbsp;in&nbsp;_load_unlocked
</td></tr>
<tr><td>2023-02-05T17:35:38.904193685Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap&gt;",&nbsp;line&nbsp;1006,&nbsp;in&nbsp;_find_and_load_unlocked
</td></tr>
<tr><td>2023-02-05T17:35:38.904144015Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap&gt;",&nbsp;line&nbsp;1027,&nbsp;in&nbsp;_find_and_load
</td></tr>
<tr><td>2023-02-05T17:35:38.904034507Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"&lt;frozen&nbsp;importlib._bootstrap&gt;",&nbsp;line&nbsp;1050,&nbsp;in&nbsp;_gcd_import
</td></tr>
<tr><td>2023-02-05T17:35:38.903984181Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_bootstrap._gcd_import(name[level:],&nbsp;package,&nbsp;level)
</td></tr>
<tr><td>2023-02-05T17:35:38.903699643Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/importlib/__init__.py",&nbsp;line&nbsp;126,&nbsp;in&nbsp;import_module
</td></tr>
<tr><td>2023-02-05T17:35:38.903659838Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;import_module(import_name)
</td></tr>
<tr><td>2023-02-05T17:35:38.903389731Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/site-packages/hypercorn/utils.py",&nbsp;line&nbsp;115,&nbsp;in&nbsp;load_application
</td></tr>
<tr><td>2023-02-05T17:35:38.903336012Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;load_application(config.application_path,&nbsp;config.wsgi_max_body_size)
</td></tr>
<tr><td>2023-02-05T17:35:38.903072254Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/site-packages/hypercorn/run.py",&nbsp;line&nbsp;41,&nbsp;in&nbsp;run
</td></tr>
<tr><td>2023-02-05T17:35:38.903033821Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;run(config)
</td></tr>
<tr><td>2023-02-05T17:35:38.902821825Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.10/site-packages/hypercorn/__main__.py",&nbsp;line&nbsp;287,&nbsp;in&nbsp;main
</td></tr>
<tr><td>2023-02-05T17:35:38.902765897Z</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;sys.exit(main())
</td></tr>
<tr><td>2023-02-05T17:35:38.902143064Z</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/bin/hypercorn",&nbsp;line&nbsp;8,&nbsp;in&nbsp;&lt;module&gt;
</td></tr>
<tr><td>2023-02-05T17:35:38.901557352Z</td><td>stdout</td><td>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
</td></tr>
<tr><td>2023-02-05T17:35:38.150407205Z</td><td>stdout</td><td>更新成功...
</td></tr>
<tr><td>2023-02-05T17:35:38.149805424Z</td><td>stdout</td><td>HEAD&nbsp;is&nbsp;now&nbsp;at&nbsp;4660cc8&nbsp;Merge&nbsp;pull&nbsp;request&nbsp;#7&nbsp;from&nbsp;DDS-Derek/main
</td></tr>
<tr><td>2023-02-05T17:35:38.137127277Z</td><td>stdout</td><td>&nbsp;*&nbsp;branch&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&gt;&nbsp;FETCH_HEAD
</td></tr>
<tr><td>2023-02-05T17:35:38.137012391Z</td><td>stdout</td><td>From&nbsp;https://github.com/Steve0x2a/DLimiter
</td></tr>
<tr><td>2023-02-05T17:35:38.133083146Z</td><td>stdout</td><td>remote:&nbsp;Total&nbsp;0&nbsp;(delta&nbsp;0),&nbsp;reused&nbsp;0&nbsp;(delta&nbsp;0),&nbsp;pack-reused&nbsp;0[K
</td></tr>
<tr><td>2023-02-05T17:35:36.951019484Z</td><td>stdout</td><td>更新程序...
</td></tr>
</table></body></html>

**Comment by Steve0x2a** [comment]
> 大佬，麻烦看看报错怎么回事 下面是docker的日志
> 
> <style>body{font-family:"Lucida Console",Consola,Monaco,Monospace,"Courier New",Courier,Serif;}h2{text-align:center;}table{width:95%;border-collapse:collapse;}table,th,td{border:1px solid black;}td{white-space:nowrap;text-align:left;}</style>
> ## Dlimiter1
> date	stream	content
> 2023-02-05T17:35:38.905740266Z	stdout	_rtoml.TomlParsingError: unexpected character found: `\u{89e6}` at line 21 column 20
> 2023-02-05T17:35:38.905641986Z	stdout	    return _rtoml.deserialize(toml)
> 2023-02-05T17:35:38.905554722Z	stdout	  File "/usr/local/lib/python3.10/site-packages/rtoml/__init__.py", line 35, in loads
> 2023-02-05T17:35:38.905518666Z	stdout	    return loads(toml)
> 2023-02-05T17:35:38.905302217Z	stdout	  File "/usr/local/lib/python3.10/site-packages/rtoml/__init__.py", line 26, in load
> 2023-02-05T17:35:38.905268466Z	stdout	    cfg = edict(rtoml.load(Path(self.path)))
> 2023-02-05T17:35:38.905229675Z	stdout	  File "/app/conf/__init__.py", line 14, in parse_conf
> 2023-02-05T17:35:38.905179948Z	stdout	    config = Config(path="./conf/config.toml").parse_conf()
> 2023-02-05T17:35:38.905095987Z	stdout	  File "/app/conf/__init__.py", line 21, in <module>
> 2023-02-05T17:35:38.905057739Z	stdout	    from conf import config
> 2023-02-05T17:35:38.904902781Z	stdout	  File "/app/utils/limiter.py", line 1, in <module>
> 2023-02-05T17:35:38.904871203Z	stdout	    from utils.limiter import player_apply_limit
> 2023-02-05T17:35:38.904824378Z	stdout	  File "/app/routes/emby.py", line 3, in <module>
> 2023-02-05T17:35:38.904783498Z	stdout	    from routes.emby import bp_emby
> 2023-02-05T17:35:38.904716885Z	stdout	  File "/app/routes/__init__.py", line 2, in <module>
> 2023-02-05T17:35:38.904676582Z	stdout	    from routes import bp_player
> 2023-02-05T17:35:38.904578447Z	stdout	  File "/app/main.py", line 2, in <module>
> 2023-02-05T17:35:38.904491304Z	stdout	  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2023-02-05T17:35:38.904392526Z	stdout	  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
> 2023-02-05T17:35:38.904284603Z	stdout	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
> 2023-02-05T17:35:38.904193685Z	stdout	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
> 2023-02-05T17:35:38.904144015Z	stdout	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
> 2023-02-05T17:35:38.904034507Z	stdout	  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
> 2023-02-05T17:35:38.903984181Z	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
> 2023-02-05T17:35:38.903699643Z	stdout	  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
> 2023-02-05T17:35:38.903659838Z	stdout	    module = import_module(import_name)
> 2023-02-05T17:35:38.903389731Z	stdout	  File "/usr/local/lib/python3.10/site-packages/hypercorn/utils.py", line 115, in load_application
> 2023-02-05T17:35:38.903336012Z	stdout	    load_application(config.application_path, config.wsgi_max_body_size)
> 2023-02-05T17:35:38.903072254Z	stdout	  File "/usr/local/lib/python3.10/site-packages/hypercorn/run.py", line 41, in run
> 2023-02-05T17:35:38.903033821Z	stdout	    run(config)
> 2023-02-05T17:35:38.902821825Z	stdout	  File "/usr/local/lib/python3.10/site-packages/hypercorn/__main__.py", line 287, in main
> 2023-02-05T17:35:38.902765897Z	stdout	    sys.exit(main())
> 2023-02-05T17:35:38.902143064Z	stdout	  File "/usr/local/bin/hypercorn", line 8, in <module>
> 2023-02-05T17:35:38.901557352Z	stdout	Traceback (most recent call last):
> 2023-02-05T17:35:38.150407205Z	stdout	更新成功...
> 2023-02-05T17:35:38.149805424Z	stdout	HEAD is now at 4660cc8 Merge pull request #7 from DDS-Derek/main
> 2023-02-05T17:35:38.137127277Z	stdout	 * branch            main       -> FETCH_HEAD
> 2023-02-05T17:35:38.137012391Z	stdout	From https://github.com/Steve0x2a/DLimiter
> 2023-02-05T17:35:38.133083146Z	stdout	remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0�[K
> 2023-02-05T17:35:36.951019484Z	stdout	更新程序...

@flyjinhui 目测是你的配置格式不正确

**Comment by Steve0x2a** [comment]
如果还有问题，请另开issue
